### ISSUE TITLE
missing staticman partial

### ISSUE THREAD

**Issue by mattumotu** [JulioV/blog_comments#32]
Hi Julio,

I read your post on hugo and staticman here: https://dev.to/julio_ui/configuring-staticman-comments-with-hugo-317g

But the partial, css and js it links to all 404 on github,
I see the comments in this repo saying they are updated, but these comments don't appear on your post on dev.to, and I can't find your blog showing these links(!)

Could you please update the above article with the new links?

many thanks,
Matt

**Comment by JulioV** [comment]
I’ve also updated the post in Dev.to
